projects:
  app:
    schemaPath: "src/schemas/app.graphql"
    extensions:
      endpoints:
        default: "http://localhost:4000"
  database:
    schemaPath: "src/schemas/database.graphql"
    extensions:
      graphcool: graphcool.yml
